import numpy as np 
import matplotlib.pyplot as plt 

'''Class for analyzing the time spent by a function of part of a program
and subdivide its parts in a pie chart. The analyzes takes a core file into
account, which is a log file generated by the targetted software. 

The current version supports this type of log format (ignore '>'):
	> func_name1: 45.2 sec
	> func_name2: 2.0 sec
	> ...
	> func_name1897: 12.7 sec
	> total (big func): 15897 sec
'''

TOTAL = "total"

class Analyzer:
	# init arg: the path/name of the log file
	def __init__(self, file):
		self.file = file
		self.func_time = {}
		self.total = {}

	# scans the log line by line
	def scan(self):
		with open(self.file) as f:
			for line in f:
				func, time = line.split(': ')
				time = time.split(' sec')[0]
				if TOTAL in func.lower():
					self.total[func] = float(time)
				else:
					self.func_time[func] = float(time)

	# generates a pie chart
	def plot(self):
		# utility func to print the values
		def text_plot(pct, values):
		    absolute = pct/100.*np.sum(values)
		    return "{:.1f}%\n({:.1f} s)".format(pct, absolute)

		fig, ax = plt.subplots(1, 2, figsize=(10,5))

		# total func
		ax[0].pie(list(self.total.values()), 
			   labels=list(self.total.keys()),
			   autopct=lambda pct: text_plot(pct, list(self.total.values())),
			   radius=1.2)

		# subfuncs
		ax[1].pie(list(self.func_time.values()), 
			   labels=list(self.func_time.keys()),
			   autopct=lambda pct: text_plot(pct, list(self.func_time.values())),
			   radius=1.2)
		self.fig = fig
		return fig, ax

	# save the pie chart. Arg is the name of the out png (ex: "myfig" (no extension))
	# and a specific path.
	def save(self, figname, path="", dpi=300):
		if path != "" and path[-1] != '/' and path[-1] != '\\':
			path += '/'
		self.fig.savefig(path + figname + ".png", dpi=dpi)
		
		if path=="":
			path = "ROOT/"
		print("File saved as " + figname.split('/')[-1].split('\\')[-1] + ".png in " + path)